// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package portsmocks

import (
	"context"
	"delivery/internal/core/domain/model/courier"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewCourierRepositoryMock creates a new instance of CourierRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCourierRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *CourierRepositoryMock {
	mock := &CourierRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CourierRepositoryMock is an autogenerated mock type for the CourierRepository type
type CourierRepositoryMock struct {
	mock.Mock
}

type CourierRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *CourierRepositoryMock) EXPECT() *CourierRepositoryMock_Expecter {
	return &CourierRepositoryMock_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type CourierRepositoryMock
func (_mock *CourierRepositoryMock) Add(ctx context.Context, aggregate *courier.Courier) error {
	ret := _mock.Called(ctx, aggregate)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *courier.Courier) error); ok {
		r0 = returnFunc(ctx, aggregate)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CourierRepositoryMock_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type CourierRepositoryMock_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - aggregate *courier.Courier
func (_e *CourierRepositoryMock_Expecter) Add(ctx interface{}, aggregate interface{}) *CourierRepositoryMock_Add_Call {
	return &CourierRepositoryMock_Add_Call{Call: _e.mock.On("Add", ctx, aggregate)}
}

func (_c *CourierRepositoryMock_Add_Call) Run(run func(ctx context.Context, aggregate *courier.Courier)) *CourierRepositoryMock_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *courier.Courier
		if args[1] != nil {
			arg1 = args[1].(*courier.Courier)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CourierRepositoryMock_Add_Call) Return(err error) *CourierRepositoryMock_Add_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CourierRepositoryMock_Add_Call) RunAndReturn(run func(ctx context.Context, aggregate *courier.Courier) error) *CourierRepositoryMock_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type CourierRepositoryMock
func (_mock *CourierRepositoryMock) Get(ctx context.Context, ID uuid.UUID) (*courier.Courier, error) {
	ret := _mock.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *courier.Courier
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*courier.Courier, error)); ok {
		return returnFunc(ctx, ID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *courier.Courier); ok {
		r0 = returnFunc(ctx, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*courier.Courier)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CourierRepositoryMock_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type CourierRepositoryMock_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - ID uuid.UUID
func (_e *CourierRepositoryMock_Expecter) Get(ctx interface{}, ID interface{}) *CourierRepositoryMock_Get_Call {
	return &CourierRepositoryMock_Get_Call{Call: _e.mock.On("Get", ctx, ID)}
}

func (_c *CourierRepositoryMock_Get_Call) Run(run func(ctx context.Context, ID uuid.UUID)) *CourierRepositoryMock_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CourierRepositoryMock_Get_Call) Return(courier1 *courier.Courier, err error) *CourierRepositoryMock_Get_Call {
	_c.Call.Return(courier1, err)
	return _c
}

func (_c *CourierRepositoryMock_Get_Call) RunAndReturn(run func(ctx context.Context, ID uuid.UUID) (*courier.Courier, error)) *CourierRepositoryMock_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type CourierRepositoryMock
func (_mock *CourierRepositoryMock) GetAll(ctx context.Context) ([]*courier.Courier, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*courier.Courier
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*courier.Courier, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*courier.Courier); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*courier.Courier)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CourierRepositoryMock_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type CourierRepositoryMock_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *CourierRepositoryMock_Expecter) GetAll(ctx interface{}) *CourierRepositoryMock_GetAll_Call {
	return &CourierRepositoryMock_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *CourierRepositoryMock_GetAll_Call) Run(run func(ctx context.Context)) *CourierRepositoryMock_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CourierRepositoryMock_GetAll_Call) Return(couriers []*courier.Courier, err error) *CourierRepositoryMock_GetAll_Call {
	_c.Call.Return(couriers, err)
	return _c
}

func (_c *CourierRepositoryMock_GetAll_Call) RunAndReturn(run func(ctx context.Context) ([]*courier.Courier, error)) *CourierRepositoryMock_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllFree provides a mock function for the type CourierRepositoryMock
func (_mock *CourierRepositoryMock) GetAllFree(ctx context.Context) ([]*courier.Courier, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllFree")
	}

	var r0 []*courier.Courier
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*courier.Courier, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*courier.Courier); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*courier.Courier)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CourierRepositoryMock_GetAllFree_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllFree'
type CourierRepositoryMock_GetAllFree_Call struct {
	*mock.Call
}

// GetAllFree is a helper method to define mock.On call
//   - ctx context.Context
func (_e *CourierRepositoryMock_Expecter) GetAllFree(ctx interface{}) *CourierRepositoryMock_GetAllFree_Call {
	return &CourierRepositoryMock_GetAllFree_Call{Call: _e.mock.On("GetAllFree", ctx)}
}

func (_c *CourierRepositoryMock_GetAllFree_Call) Run(run func(ctx context.Context)) *CourierRepositoryMock_GetAllFree_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CourierRepositoryMock_GetAllFree_Call) Return(couriers []*courier.Courier, err error) *CourierRepositoryMock_GetAllFree_Call {
	_c.Call.Return(couriers, err)
	return _c
}

func (_c *CourierRepositoryMock_GetAllFree_Call) RunAndReturn(run func(ctx context.Context) ([]*courier.Courier, error)) *CourierRepositoryMock_GetAllFree_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type CourierRepositoryMock
func (_mock *CourierRepositoryMock) Update(ctx context.Context, aggregate *courier.Courier) error {
	ret := _mock.Called(ctx, aggregate)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *courier.Courier) error); ok {
		r0 = returnFunc(ctx, aggregate)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CourierRepositoryMock_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type CourierRepositoryMock_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - aggregate *courier.Courier
func (_e *CourierRepositoryMock_Expecter) Update(ctx interface{}, aggregate interface{}) *CourierRepositoryMock_Update_Call {
	return &CourierRepositoryMock_Update_Call{Call: _e.mock.On("Update", ctx, aggregate)}
}

func (_c *CourierRepositoryMock_Update_Call) Run(run func(ctx context.Context, aggregate *courier.Courier)) *CourierRepositoryMock_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *courier.Courier
		if args[1] != nil {
			arg1 = args[1].(*courier.Courier)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CourierRepositoryMock_Update_Call) Return(err error) *CourierRepositoryMock_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CourierRepositoryMock_Update_Call) RunAndReturn(run func(ctx context.Context, aggregate *courier.Courier) error) *CourierRepositoryMock_Update_Call {
	_c.Call.Return(run)
	return _c
}
